# Generated by Django 5.2.15 on 2026-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dormitory_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dormitory_room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_dormitory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tuition_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
