# Generated by Django 5.2.15 on 2026-08-30 14:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_radius_meters',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='course',
            name='require_attendance_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance_latitude__isnull', True), ('attendance_longitude__isnull', True)), models.Q(('attendance_latitude__isnull', False), ('attendance_longitude__isnull', False)), _connector='OR'), name='course_attendance_coordinates_are_paired'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_radius_meters__gte', 10), ('attendance_radius_meters__lte', 5000)), name='course_attendance_radius_between_10_and_5000'),
        ),
    ]
