# Generated by Django 5.2.15 on 2026-08-30 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_attendance_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('require_attendance_location', False), models.Q(('attendance_latitude__isnull', False), ('attendance_longitude__isnull', False)), _connector='OR'), name='course_required_location_has_coordinates'),
        ),
    ]
